version: "3.8"

services:
  mw-share:
    image: ghcr.io/mindwerk-ai/mw-share:latest
    restart: unless-stopped
    environment:
      - TRUST_PROXY=true
    volumes:
      - mwshare-data:/opt/app/backend/data
      - mwshare-images:/opt/app/frontend/public/img

volumes:
  mwshare-data:
  mwshare-images:
